### ISSUE TITLE
problem with loadBioassay

### ISSUE THREAD

**Issue by islet-data-tinkerer** [girke-lab/bioassayR#2]
I have gotten the tutorial to work with my data up until I need to loadBioassay(). Here is what I did:
**********************
> library(cellHTS2)
> library(bioassayR)
> setwd("E:/Dropbox/1TB_Doc/R/data")
> mydb <- newBioassayDB("8kdb1", indexed=F)
Error in newBioassayDB("8kdb1", indexed = F) : 
  database filename already exists
> addDataSource(mydb, description = "other", version = "unknown")
Error in addDataSource(mydb, description = "other", version = "unknown") : 
  object 'mydb' not found
> mydb <- newBioassayDB("8kdbtest", indexed=F)
Warning messages:
1: In result_fetch(res@ptr, n = n) :
  Don't need to call dbFetch() for statements, only for queries
2: In result_fetch(res@ptr, n = n) :
  Don't need to call dbFetch() for statements, only for queries
3: In result_fetch(res@ptr, n = n) :
  Don't need to call dbFetch() for statements, only for queries
4: In result_fetch(res@ptr, n = n) :
  Don't need to call dbFetch() for statements, only for queries
5: In result_fetch(res@ptr, n = n) :
  Don't need to call dbFetch() for statements, only for queries
> addDataSource(mydb, description = "other", version = "unknown")
Warning messages:
1: Factors converted to character 
2: In result_fetch(res@ptr, n = n) :
  Don't need to call dbFetch() for statements, only for queries
> my8kdata <- read.table("8kdata_bioassayR.txt",
+                        header=TRUE,
+                        stringsAsFactors = FALSE,
+                        colClasses = c("character","character","numeric")
+ )
> myAssay <- new("bioassay", aid="123456", source_id="Kalwat",assay_type="primary",
+                    organism="mouse",scoring="Z-score", targets="1", target_types="cells", scores=my8kdata)
> myAssay
class:		 bioassay 
aid:		 123456 
source_id:	 Kalwat 
assay_type:	 primary 
organism:	 mouse 
scoring:	 Z-score 
targets:	 1 
target_types:	 cells 
total scores:	 8320 
> loadBioassay(mydb, myAssay)
Error in loadBioassay(mydb, myAssay) : 
  data source not found in database - please load it first with addDataSource
*******************
So I cannot figure out why it won't loadBioassay when I have already used addDataSource to add mydb apparently without error. I am probably just missing something very basic, but I will appreciate any help.

**Comment by TylerBackman** [comment]
The source_id for your bioassay object myAssay as created with new("bioassay") is "Kalwat", which needs to be created as a data source in the database before loading it. For example, try running:

`addDataSource(mydb, description = "Kalwat", version = "unknown")`

I know it's somewhat annoying that this is required, but the idea was that you are forced to mention which version of your data is stored in the database (such as the date it was collected), to avoid confusion and to help make it reproducible. 

Sincerely,
Tyler

**Comment by islet-data-tinkerer** [comment]
Thanks for a rapid reply, I will try that out tonight and see if it fixes my problems. Thanks for writing this program, I hope I can do something useful with it.

**Comment by TylerBackman** [comment]
No problem, feel free to ask any other questions you have.
